services:
  postgres:
    image: postgres:15-alpine
    container_name: rescom_postgres
    restart: always
    environment:
      POSTGRES_USER: rescom_admin
      POSTGRES_PASSWORD: rescom_password
      POSTGRES_DB: rescom_db
    ports:
      - "5433:5432"
    volumes:
      - rescom_pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: rescom_localstack
    restart: always
    environment:
      SERVICES: s3
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - rescom_localstack_data:/tmp/localstack

  clamav:
    image: clamav/clamav:stable
    container_name: rescom_clamav
    restart: always
    ports:
      - "3310:3310"
    volumes:
      - rescom_clamav_data:/var/lib/clamav

volumes:
  rescom_pgdata:
  rescom_localstack_data:
  rescom_clamav_data:
