version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rescom_postgres
    restart: always
    environment:
      POSTGRES_USER: rescom_admin
      POSTGRES_PASSWORD: rescom_password
      POSTGRES_DB: rescom_db
    ports:
      - "5433:5432"
    volumes:
      - rescom_pgdata:/var/lib/postgresql/data

volumes:
  rescom_pgdata:
